internalName: bxr

locales:
  en:
    name: &bundleName "Russia Buriat Keyboards"
    description: "Keyboards for Russia Buriat from the Divvun group at UiT."
  nb:
    name: "Buriat-tastatur (Russland)"
    description: "Tastatur for russisk buriat fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [bxr-mac, bxr-mobile, bxr-win]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.bxr
    icon: images/bxr-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard
    version: "1.0.0"
    build: "1"

  ios: &AppleID
    codeSignId: "2K5J2584NX"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.bxr
    bundleName: *bundleName
    icon: images/bxr-icon.png
    version: "1.0.0"
    build: "1"

  osx:
    <<: *AppleID
    icon: images/buryad.png
    version: 0.1.0
    resources: doc

  win:
    appName: *bundleName
    version: 0.1.0
    url: "http://divvun.no"
    uuid: "6E5B7847-E2F0-43A9-8B0A-D67F66F96904"
