locales:
  en:
    name: Russia Buriat Keyboards
    description: Keyboards for Russia Buriat from the Divvun group at UiT.
  nb:
    name: Buriat-tastatur (Russland)
    description: Tastatur for russisk buriat fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
