locales:
  bxr:
    name: Буряад-Монгол тобшолуур
    description: Буряад-Монгол хэлэнэй тобшолуур (Галзууд/Бадагаров/ Баяндалайн Жаргал, Норвегиин Тромсө хотын Ехэ һургуулиин Divvun бүлгэм)
  ru:
    name: Буряад-Монгол тобшолуур
    description: Клавиатура для бурятского языка, разработанная Бадагаровым Жаргалом и Divvun group (UiT)
  mn:
    name: Буриад-Монгол гарын драйвер
    description: Буриад-Монгол кирилл үсгийн гарын драйвер үүнийг Галзууд (Бадагаров) овогтой Баяндалайн Жаргал Норвегийн Divvun group-н хамт зохиов.
  en:
    name: Buryad-Mongol Keyboards
    description: Keyboard for Buryad-Mongol from Jargal Badagarov and the Divvun group at UiT.

author: Jargal Badagarov; The Divvun Group, UiT The Arctic University of Norway
copyright: (c) 2000–2019 Jargal Badagarov; (c) 2017–2019 Divvun/Giellatekno/UiT
email: bjargal@mail.ru; feedback@divvun.no
organisation: UiT The Arctic University of Norway
